# Generated by Django 2.2.5 on 2019-11-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('keyword', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='siritori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruby', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
                ('used', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='words',
            fields=[
                ('word', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mean', models.CharField(max_length=255)),
            ],
        ),
    ]
